engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "server.js"
  - config/
  - routes/
exclude_paths:
- coverage/
- node_modules/
- test/
