language: node_js
node_js:
- "4"
- "5"
- "6"
- "7"
script:
- npm run istanbul
- npm run codecov
- npm run codeclimate
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - CXX=g++-4.8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d4d24a8457af3183f2dc
    on_success: always
    on_failure: always
    on_start: never
